version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: vocab_s
    restart: always
    environment:
      POSTGRES_USER: vocab_dev
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: vocabs_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  data:
